remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
gem "github-pages", group: :jekyll_plugins
title: From Touch to Action: Enhancing Robot Manipulation Policies through Tactile Perception
description: [Webpage for ICRA 2026 Workshop, From Touch to Action: Enhancing Robot Manipulation Policies through Tactile Perception]
